//
// Created by 蔡宜身 on 2020/12/2.
//

#ifndef DATA_STRUCTURE_SCRATCHES_SRC_TRY_CATCH_H
#define DATA_STRUCTURE_SCRATCHES_SRC_TRY_CATCH_H

void oldEnough(int age);

#endif  // DATA_STRUCTURE_SCRATCHES_SRC_TRY_CATCH_H
